//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AR_Logger.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AR_Logger.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to.
        /// </summary>
        public static string AlertConnected {
            get {
                return ResourceManager.GetString("AlertConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected.
        /// </summary>
        public static string AlertDisconnected {
            get {
                return ResourceManager.GetString("AlertDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Tech.
        /// </summary>
        public static string ButtonAddTech {
            get {
                return ResourceManager.GetString("ButtonAddTech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Cases.
        /// </summary>
        public static string ButtonAssignCases {
            get {
                return ResourceManager.GetString("ButtonAssignCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string ButtonImport {
            get {
                return ResourceManager.GetString("ButtonImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Ticket.
        /// </summary>
        public static string ButtonNewTicket {
            get {
                return ResourceManager.GetString("ButtonNewTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ButtonOK {
            get {
                return ResourceManager.GetString("ButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string ButtonSelectAll {
            get {
                return ResourceManager.GetString("ButtonSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select None.
        /// </summary>
        public static string ButtonSelectNone {
            get {
                return ResourceManager.GetString("ButtonSelectNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync.
        /// </summary>
        public static string ButtonSync {
            get {
                return ResourceManager.GetString("ButtonSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts Receivable Imbalance Logger.
        /// </summary>
        public static string LabelAbout1 {
            get {
                return ResourceManager.GetString("LabelAbout1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accountz Reeceevable ain&apos;t just about bein&apos; a supastar and gettin&apos; tha benjamins. It be about skeelz. It be about HONOR..
        /// </summary>
        public static string LabelAbout2 {
            get {
                return ResourceManager.GetString("LabelAbout2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2018 | Developed by Dan Issler.
        /// </summary>
        public static string LabelAbout3 {
            get {
                return ResourceManager.GetString("LabelAbout3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imbalance Amount.
        /// </summary>
        public static string LabelAdjustImbalance {
            get {
                return ResourceManager.GetString("LabelAdjustImbalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusted Amount.
        /// </summary>
        public static string LabelAdjustNew {
            get {
                return ResourceManager.GetString("LabelAdjustNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Amount.
        /// </summary>
        public static string LabelAdjustOld {
            get {
                return ResourceManager.GetString("LabelAdjustOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction #.
        /// </summary>
        public static string LabelAdjustTrans {
            get {
                return ResourceManager.GetString("LabelAdjustTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction is from a different date!.
        /// </summary>
        public static string LabelAdjustTransDateError {
            get {
                return ResourceManager.GetString("LabelAdjustTransDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unassigned cases for this date will be divided between the selected technicians..
        /// </summary>
        public static string LabelAssignCasesHelp {
            get {
                return ResourceManager.GetString("LabelAssignCasesHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string LabelFirstDate {
            get {
                return ResourceManager.GetString("LabelFirstDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string LabelLastDate {
            get {
                return ResourceManager.GetString("LabelLastDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MainMenuAbout {
            get {
                return ResourceManager.GetString("MainMenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Details.
        /// </summary>
        public static string MainMenuAccountDetail {
            get {
                return ResourceManager.GetString("MainMenuAccountDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts Manager.
        /// </summary>
        public static string MainMenuAccountManager {
            get {
                return ResourceManager.GetString("MainMenuAccountManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Cases.
        /// </summary>
        public static string MainMenuAssign {
            get {
                return ResourceManager.GetString("MainMenuAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All Filters.
        /// </summary>
        public static string MainMenuClearFilters {
            get {
                return ResourceManager.GetString("MainMenuClearFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string MainMenuEdit {
            get {
                return ResourceManager.GetString("MainMenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MainMenuExit {
            get {
                return ResourceManager.GetString("MainMenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string MainMenuExport {
            get {
                return ResourceManager.GetString("MainMenuExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Day.
        /// </summary>
        public static string MainMenuExportDay {
            get {
                return ResourceManager.GetString("MainMenuExportDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Range.
        /// </summary>
        public static string MainMenuExportRange {
            get {
                return ResourceManager.GetString("MainMenuExportRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Week.
        /// </summary>
        public static string MainMenuExportWeek {
            get {
                return ResourceManager.GetString("MainMenuExportWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MainMenuFile {
            get {
                return ResourceManager.GetString("MainMenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string MainMenuHelp {
            get {
                return ResourceManager.GetString("MainMenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string MainMenuImport {
            get {
                return ResourceManager.GetString("MainMenuImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from WSRs.
        /// </summary>
        public static string MainMenuImportWsr {
            get {
                return ResourceManager.GetString("MainMenuImportWsr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Library.
        /// </summary>
        public static string MainMenuLibrary {
            get {
                return ResourceManager.GetString("MainMenuLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Ticket.
        /// </summary>
        public static string MainMenuTicket {
            get {
                return ResourceManager.GetString("MainMenuTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string MainMenuTools {
            get {
                return ResourceManager.GetString("MainMenuTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string MainMenuView {
            get {
                return ResourceManager.GetString("MainMenuView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        public static string MainMenuWindow {
            get {
                return ResourceManager.GetString("MainMenuWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string WindowTitleAbout {
            get {
                return ResourceManager.GetString("WindowTitleAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account History.
        /// </summary>
        public static string WindowTitleAccountHistory {
            get {
                return ResourceManager.GetString("WindowTitleAccountHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust Transaction.
        /// </summary>
        public static string WindowTitleAdjust {
            get {
                return ResourceManager.GetString("WindowTitleAdjust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Cases.
        /// </summary>
        public static string WindowTitleAssign {
            get {
                return ResourceManager.GetString("WindowTitleAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Date Range.
        /// </summary>
        public static string WindowTitleDateRange {
            get {
                return ResourceManager.GetString("WindowTitleDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string WindowTitleImport {
            get {
                return ResourceManager.GetString("WindowTitleImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AR Logger.
        /// </summary>
        public static string WindowTitleMain {
            get {
                return ResourceManager.GetString("WindowTitleMain", resourceCulture);
            }
        }
    }
}
